remote_theme: pages-themes/midnight@v0.2.0
plugins: - jekyll-remote-theme 
title: [Les meilleures audiences dans les salles de cinéma françaises]
description: [Cette présentation vise à présenter toute sorte d informations concernant les scores d’audience réalisés par les 200 films les plus plébiscités dans les salles françaises, sur une période allant de 1945 à 2020]
